-   id: no-string-hints
    name: no-string-hints
    description: Automatically remove string literals in type annotations.
    entry: no_string_hints
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
