-   id: dequote-annotations
    name: dequote-annotations
    description: Automatically remove string literals in type annotations.
    entry: dequote_annotations
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
